apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: ingress-monitoring
    annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /$2
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: letsencrypt-production
{{- if .Values.host}}
spec:
    rules:
      - host: {{ .Values.host }}
        http:
              paths:
                  - path: /monitoring(/|$)(.*)
                    pathType: Prefix
                    backend:
                        service:
                            name: monitoring-grafana
                            port:
                                number: 80
    tls:
        - hosts:
            - {{ .Values.host }}
          secretName: letsencrypt-production
{{- else}}
spec:
    rules:
      - http:
              paths:
                  - path: /monitoring(/|$)(.*)
                    pathType: Prefix
                    backend:
                        service:
                            name: monitoring-grafana
                            port:
                                number: 80
{{- end}}