{
 "title": "Fission",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Controller",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count_over_time({svc=\"controller\"} |= \"\\\"level\\\":\\\"info\\\"\" [1h])",
     "legendFormat": "Success"
    },
    {
     "expr": "count_over_time({svc=\"controller\"} |= \"\\\"level\\\":\\\"error\\\"\" [1h])",
     "legendFormat": "Error"
    }
   ]
  },
  {
   "title": "Router",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count_over_time({svc=\"router\"} |= \"\\\"level\\\":\\\"info\\\"\" [1h] )",
     "legendFormat": "Success"
    },
    {
     "expr": "count_over_time({svc=\"router\"} |= \"\\\"level\\\":\\\"error\\\"\" [1h] )",
     "legendFormat": "Error"
    }
   ]
  },
  {
   "title": "NewDeploy",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count_over_time({svc=\"executor\"} |= \"newdeploy\" |= \"\\\"level\\\":\\\"info\\\"\" [1h] )",
     "legendFormat": "Success"
    },
    {
     "expr": "count_over_time({svc=\"executor\"} |= \"newdeploy\" |= \"\\\"level\\\":\\\"error\\\"\" [1h] )",
     "legendFormat": "Error"
    }
   ]
  },
  {
   "title": "PoolManager",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count_over_time({svc=\"executor\"} |= \"pool\" |= \"\\\"level\\\":\\\"info\\\"\" [1h] )",
     "legendFormat": "Success"
    },
    {
     "expr": "count_over_time({svc=\"executor\"} |= \"pool\" |= \"\\\"level\\\":\\\"error\\\"\" [1h] )",
     "legendFormat": "Error"
    }
   ]
  },
  {
   "title": "Builder",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"fission-builder\"}[5m])) by (envName)"
    }
   ]
  },
  {
   "title": "Functions",
   "type": "graph",
   "gridPos": { "h": 5, "w": 11, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"fission\"} |= \"\\\"level\\\":\\\"info\\\"\"[1h]))",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(count_over_time({namespace=\"fission\"} |= \"\\\"level\\\":\\\"error\\\"\"[1h]))",
     "legendFormat": "Error"
    },
    {
     "expr": "sum(count_over_time({namespace=\"fission\"} |= \"\\\"level\\\":\\\"fatal\\\"\"[1h]))",
     "legendFormat": "Fatal"
    }
   ]
  }
 ]
}