apiVersion: stash.appscode.com/v1beta1
kind: BackupConfiguration
metadata:
  name: cockatoo-backup
  namespace: { { .Release.Namespace } }
spec:
  schedule: '*/5 * * * *'
  task:
    name: postgres-backup-14.0
  repository:
    name: cockatoo-backup-repo
  target:
    ref:
      apiVersion: appcatalog.appscode.com/v1alpha1
      kind: AppBinding
      name: cockatoo
  retentionPolicy:
    name: keep-last-5
    keepLast: 5
    prune: true
