apiVersion: v1
kind: Secret
metadata:
  name: bucket-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  RESTIC_PASSWORD: {{ .Values.encryptionKey | b64enc }}
  AWS_ACCESS_KEY_ID: {{ .Values.s3.accessKey | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.s3.secret | b64enc }}