apiVersion: kubedb.com/v1alpha2
kind: Postgres
metadata:
  name: cockatoo
  namespace: db
spec:
  version: "14.1"
  storageType: Durable
  storage:
    storageClassName: "csi-cinder-sc-retain"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  terminationPolicy: DoNotTerminate
