kind: ConfigMap 
apiVersion: v1 
metadata:
  name: flyway-migration-scripts
  labels:
    name: flyway-migration-scripts
    app: auth
data:
  {{- (.Files.Glob "migrations/*.sql").AsConfig | nindent 2 }}