name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Start minikube
        uses: medyagh/setup-minikube@master
      - name: Try the cluster !
        run: kubectl get pods -A
      - name: Get Helm
        run: curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
      - name: Prepare Helm install
        run: chmod 700 get_helm.sh
      - name: Helm install
        run: ./get_helm.sh
      - name: Get Fission
        run: wget  https://github.com/fission-suite/fission/releases/download/2.17.0/fission-cli-ubuntu-20.04-x86_64
      - name: Prepare Fission install
        run: chmod a+x ./fission-cli-ubuntu-20.04-x86_64
      - name: Fission install
        run: sudo mv fission-cli-ubuntu-20.04-x86_64 /usr/local/bin/fission
      - name: Finalize Fission install
        run: export PATH=/usr/local/bin:$PATH
      - name: Check Kubectl
        run: kubectl version
      - name: Check Helm
        run: helm version
      - name: Check Fission
        run: fission version
      - name: Check Python
        run: python --version
