name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check npm
        run: npm --version
      - name: npm install
        run: cd k8s && npm install && npm run build
      - name: Start minikube
        uses: medyagh/setup-minikube@master
      - name: Get Helm
        run: curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
      - name: Prepare Helm install
        run: chmod 700 get_helm.sh
      - name: Helm install
        run: ./get_helm.sh
      - name: Get Fission
        run: curl -Lo fission https://github.com/fission/fission/releases/download/v1.15.1/fission-v1.15.1-linux-amd64
      - name: Prepare Fission install
        run: chmod +x fission
      - name: Fission install
        run: sudo mv fission /usr/local/bin/
      - name: Check Kubectl
        run: kubectl version
      - name: Check Helm
        run: helm version
      - name: Check Python
        run: python --version
      - name: Install pip dependencies
        run: pip install -r requirements.txt
      - name: cinstall
        run: python scripts/cinstall.py full --updateDependencies
      - name: Test Cluster
        run: python scripts/testcluster.py
